### PR TITLE
Functioning weapon reload system

### PR DESCRIPTION
**Pull request by Rumodeus**

### CODE REVIEW

**Comment by Rumodeus** [comment]
menu UI still needs to be updated to cater for keybind changes
campfires are G now

**Review by snavu — COMMENTED** [review]
- ammo UI only needs one .png of a single bullet
- the implementation of current ammo count should be similar to the implementation of food UI and food count
- refactor multiple `if` statements and variable declarations with a `for` loop and array

**Review by snavu — COMMENTED** [review]
- missing logic for reloading based on remaining bullet count
- current logic will reload mag to full capacity, even if remaining ammo count is less than full mag

**Comment by Rumodeus** [comment]
yeah i accidently deleted the logic whoopsies

**Pull request merged**
